abrt/faf

faf.spec.in
src/pyfaf/actions/mark_probably_fixed.py
src/pyfaf/queries.py
src/pyfaf/solutionfinders/Makefile.am
src/pyfaf/solutionfinders/__init__.py
src/pyfaf/solutionfinders/prefilter_solution_finder.py
src/pyfaf/solutionfinders/probable_fix_solution_finder.py
src/pyfaf/storage/migrations/versions/272e6a3deea4_link_probable_fix_to_build.py
src/pyfaf/storage/problem.py
src/webfaf2/reports.py
src/webfaf2/templates/problems/item.html
tests/mark_probably_fixed
tests/sample_reports/Makefile.am
tests/sample_reports/ureport_systemd2
tests/sample_reports/ureport_systemd77

Add probable fix solution finder

---

src/pyfaf/opsys/__init__.py
src/pyfaf/opsys/centos.py
src/pyfaf/opsys/fedora.py
src/pyfaf/opsys/rhel.py
src/pyfaf/problemtypes/__init__.py
src/pyfaf/problemtypes/core.py
src/pyfaf/problemtypes/java.py
src/pyfaf/problemtypes/kerneloops.py
src/pyfaf/problemtypes/python.py
src/pyfaf/ureport.py

pyfaf: pass count parameter to os and problem plugins save_ureport

---

src/pyfaf/actions/pull_releases.py

pyfaf: fix release updating in pull-releases action

---

src/pyfaf/solutionfinders/__init__.py
tests/webfaf/reports

This functionality could be used by blueprint plugins.

Improve solution finders

---

config/plugins/Makefile.am
config/plugins/ruby.conf
faf.spec.in
src/pyfaf/problemtypes/Makefile.am
src/pyfaf/problemtypes/ruby.py
tests/actions
tests/faftests/__init__.py
tests/sample_reports/Makefile.am
tests/sample_reports/ureport_ruby
tests/save_reports
tests/ureport

`ruby.py` has been adopted from `python.py`.

Problemtype Ruby

---

src/pyfaf/actions/match_unknown_packages.py
src/pyfaf/queries.py
src/pyfaf/storage/opsys.py
src/pyfaf/storage/report.py
src/webfaf2/forms.py
src/webfaf2/problems.py
src/webfaf2/reports.py
src/webfaf2/static/css/style.css
src/webfaf2/templates/problems/list.html

Fixes issues that appeared after deploying the version filter.

Post version filter fixes

---

src/pyfaf/actions/reposync.py

Allows syncing of builds from a repo without downloading the
packages or deleting the packages after processing of
dependencies. Useful for OpenShift or Docker instances where
storage is limited and retracing (where downloaded packages are
required) is not being done anyway.

pyfaf: add reposync --no-download-rpm and --no-store-rpm

---

src/webfaf2/forms.py
src/webfaf2/problems.py
src/webfaf2/templates/problems/list.html

webfaf: add bug status filter

---

src/webfaf2/problems.py
src/webfaf2/reports.py
src/webfaf2/templates/problems/item.html
src/webfaf2/templates/reports/item.html

According to #417 
Use the `extfafadd` action to add external FAF instances.

Extfaf link

---

src/pyfaf/actions/retrace.py
src/pyfaf/problemtypes/kerneloops.py

Two little fixes for exceptions in retracing.

Fix retrace

---

src/pyfaf/actions/create_problems.py
tests/create_problems

https://github.com/abrt/faf/wiki/Create-problems-(clustering)

Create problems documentation and clarification

---

src/pyfaf/storage/problem.py
src/webfaf2/filters.py

Problem will be marked "FIXED" iff all bugs associated with it are closed and
at least one has resolution NEXTRELEASE, CURRENTRELEASE, RAWHIDE or ERRATA.
Closes #429

webfaf2: add "FIXED" status for problem bugs

---

CHANGELOG.md
config/faf.conf.in
src/pyfaf/storage/migrations/versions/50d3e87e4b2a_add_reporturl.py
src/pyfaf/storage/migrations/versions/Makefile.am
src/pyfaf/storage/problem.py
src/pyfaf/storage/report.py
src/pyfaf/ureport.py
src/webfaf/static/css/style.css
src/webfaf/templates/_helpers.html
src/webfaf/templates/problems/item.html
src/webfaf/templates/problems/list.html
src/webfaf/templates/problems/list_table_rows.html
src/webfaf/templates/reports/item.html
tests/faftests/test_config.conf
tests/sample_reports/Makefile.am
tests/sample_reports/url_attachment
tests/ureport

Also adds attachment filtering support.

URL attachment saving

---

faf.spec.in
src/pyfaf/problemtypes/core.py
src/pyfaf/problemtypes/java.py
src/pyfaf/problemtypes/kerneloops.py
src/pyfaf/problemtypes/python.py
src/pyfaf/problemtypes/ruby.py
src/pyfaf/utils/Makefile.am
src/pyfaf/utils/hash.py
tests/utils

Some reports caused problem during saving due to unicode decoding errors.

fix hashing & unicode

---

src/pyfaf/bugtrackers/bugzilla.py
src/pyfaf/bugtrackers/mantisbt.py
src/pyfaf/common.py
tests/bugzilla

Unsorted fixes to bugtrackers. Mainly less log spam during init & some bugs fixed.

Bugtracker fixes

---

faf.spec.in
src/pyfaf/actions/Makefile.am
src/pyfaf/actions/hash_paths.py
src/pyfaf/utils/hash.py
tests/utils

For replacing private part of the path with hash.

add hash-paths action

---

src/pyfaf/actions/repoassign.py
src/pyfaf/ureport.py

Complete saving url attachement to database
Improved repoassign for rhel

Fixing bug for setup FAF

---

src/pyfaf/repos/rpm_metadata.py
src/pyfaf/storage/migrations/versions/89d35a57f82b_add_new_value_to_repo_types_enum.py
src/pyfaf/storage/migrations/versions/Makefile.am
src/pyfaf/storage/opsys.py

This pull request makes changes necessary for configuring repo instances with the 'rpmmetadata' type.

Hook RpmMetadata in FAF database

---

src/pyfaf/queries.py

credits go to Jakub Filak. Thanks!

pyfaf: fix the get_report query

---

faf.spec.in
src/pyfaf/storage/migrations/versions/183a15e52a4f_report_history_unique.py
src/pyfaf/storage/migrations/versions/Makefile.am
src/pyfaf/storage/report.py
src/pyfaf/ureport.py
src/webfaf/reports.py
src/webfaf/static/js/Makefile.am
src/webfaf/static/js/color.js
src/webfaf/templates/_helpers.html
src/webfaf/templates/reports/item.html

In this pull-request i made showing reports per machine (unique) on report page. The older view is still available after click on button "hide unique" - it's work as switch.
Also here was change the range of date, because for large range was text unreadable. The range is now set to 20 days, week and month.

Reports per machine # 484

---

src/pyfaf/queries.py
src/pyfaf/storage/bugzilla.py
src/pyfaf/storage/mantisbt.py
src/pyfaf/storage/opsys.py
src/pyfaf/storage/problem.py
src/webfaf/reports.py

In this pull request i made a HTTP API which provides data for our statistic aggregator.

HTTP API for statistic aggregator

---

autogen.sh

Usage:
autogen.sh [sydeps [--install-yum|--install-dnf]]
Options:
sysdeps              prints out all dependencies
--install-yum      install all dependencies ('sudo yum install $DEPS')
--install-dnf      install all dependencies ('sudo dnf install $DEPS')
Signed-off-by: Matej Habrnal <mhabrnal@redhat.com>

autogen: add function which installs dependencies

---

src/pyfaf/storage/migrations/script.py.mako

storage: Update year in alembic template

---

src/pyfaf/storage/migrations/versions/168c63b81f85_report_history_default_value.py
src/pyfaf/storage/migrations/versions/Makefile.am
src/pyfaf/storage/report.py
src/webfaf/reports.py

Set default value in alembic revision and histories model

---

config/Makefile.am
config/faf
faf.spec.in

Added simple logrotate config file with just default values, similar to one in retrace-server.

Added logrotate config.

---

CHANGELOG.md
Makefile.am

It has been a while since last release was done. This could help making releases easier.

Enable creating releases with makefile

---

config/faf-web.conf.in

This change will allow to run multiple applications that use mod_wsgi
on one host.

config: Change WSGI process group

---

CHANGELOG.md

I tried to select some bigger and noticeable changes. But since from
last release there were more 300 commits and I don't really know what
was happening back then, I just selected what was clear to me.
I hope from now on the changelog will updated regularly.

changelog: Update after a while

---

faf.spec.in
src/pyfaf/actions/Makefile.am
src/pyfaf/actions/check_repo.py
tests/actions

This action can check repositories and print out if the URLs are
available and if the repo is assigned.

actions: Add action for checking repositories

---

src/pyfaf/bugtrackers/bugzilla.py
src/pyfaf/storage/bugzilla.py
src/pyfaf/storage/migrations/versions/Makefile.am
src/pyfaf/storage/migrations/versions/acd3d9bf85d1_ignore_private_bz.py
src/pyfaf/ureport.py
tests/bugzilla
tests/ureport
tests/webfaf/reports

Ignore private bugzilla

---

docker/Dockerfile
docker/Makefile
docker/README.md
docker/files/init_db
docker/files/run_faf

If run for the first time (docker run), then a new DB is created.
If starting stopped container, then start DB and check for new
migrations.

docker: Automatic starting of db

---

config/faf.conf.in
src/pyfaf/opsys/centos.py
src/pyfaf/opsys/fedora.py
src/webfaf/reports.py
src/webfaf/templates/reports/item.html

As respsonse to:
abrt/libreport#503
abrt/abrt#1266
abrt/satyr#262

Unpackaged from packages

---

src/pyfaf/problemtypes/kerneloops.py

Due to https://github.com/torvalds/linux/commit/bb5e5ce545f2 now stack
dump does not contain addresses. This is problem, since FAF expects
them. It would be probably possible to get them by ABRT, but from the
commit message it seems like they are not necessary.
I can only see problem while creating problems, since it may be harder
to differentiate one problem from another.

kerneloops: Accept oopses without address

---

src/pyfaf/storage/problem.py
src/pyfaf/storage/report.py
src/webfaf/static/css/style.css
src/webfaf/templates/_helpers.html
src/webfaf/templates/problems/item.html
src/webfaf/templates/reports/item.html

Order external urls

---

README.rst

Contribution guidelines  link was broken in README.rst

Contribution guidelines link is broken

---

src/pyfaf/common.py
src/pyfaf/storage/__init__.py

Enable loading all events from storage

Load events

---

src/pyfaf/actions/c2p.py
src/pyfaf/actions/sf_prefilter_patshow.py
src/pyfaf/actions/sf_prefilter_solshow.py
src/pyfaf/storage/fixtures/__init__.py
src/pyfaf/storage/migrations/versions/1c4d6317721a_support_mirrors.py
src/webfaf/reports.py

All `print` statements are replaced with a `print()` function
to be compatible with Python 3.

py3 compatibility: print statement is replaced with a print() function

---

faf.spec.in
pylintrc

but for now ignore the results as we have LOOOOT warnings

run pylint during buildtime

---

src/pyfaf/storage/migrations/versions/71905f91e7b7_add_archived_reports.py
src/pyfaf/storage/migrations/versions/Makefile.am
src/pyfaf/storage/problem.py
src/pyfaf/storage/report.py
src/webfaf/reports.py
src/webfaf/static/css/style.css
src/webfaf/static/js/custom.js
src/webfaf/templates/problems/item.html
src/webfaf/templates/reports/item.html
src/webfaf/templates/reports/list_table_rows.html

Can you, @mkutlak please test this?
Mind you, the user that is archiving must be in DB. So if you will be logged in as administrator, make sure that "admin" exists in DB in table `users`.

Enable archiving reports

---

src/webfaf/forms.py
src/webfaf/reports.py
src/webfaf/templates/reports/list.html

webfaf: Intuitive reports time filtering

---

src/webfaf/static/css/style.css
src/webfaf/templates/problems/list.html

This is first idea, I am more than happy to talk about what to write there

webfaf: Explain filtering by version

---

config/plugins/fedorabz.conf
config/plugins/rhelbz.conf
src/pyfaf/bugtrackers/bugzilla.py
tests/bugzilla

bugzilla: Do not always pull comments and attachments

---

src/pyfaf/actions/check_repo.py
src/pyfaf/actions/extfafclonebz.py
src/pyfaf/actions/extfaflink.py
src/pyfaf/actions/pull_reports.py
src/pyfaf/actions/reposync.py
src/pyfaf/opsys/fedora.py
src/pyfaf/repos/yum.py
src/pyfaf/storage/fixtures/__init__.py
src/webfaf/reports.py
src/webfaf/utils.py

py3: Move urllib,urllib2 and urlparse

---

faf.spec.in
src/pyfaf/actions/pull_reports.py
src/pyfaf/actions/repoimport.py
src/pyfaf/actions/retrace.py
src/pyfaf/bugtrackers/bugzilla.py
src/pyfaf/celery_tasks/__init__.py
src/pyfaf/config.py
src/pyfaf/problemtypes/kerneloops.py
src/pyfaf/utils/contextmanager.py
src/webfaf/dumpdirs.py
src/webfaf/webfaf_main.py

Others found bugs reported in #672

Fix importing errors

---

src/pyfaf/actions/__init__.py
src/pyfaf/actions/assign_release_to_builds.py
src/pyfaf/actions/cleanup_packages.py
src/pyfaf/actions/repoassign.py
src/pyfaf/bugtrackers/__init__.py
src/pyfaf/bugtrackers/bugzilla.py
src/pyfaf/bugtrackers/mantisbt.py
src/pyfaf/bugtrackers/rhelbz.py
src/pyfaf/cmdline.py
src/pyfaf/problemtypes/__init__.py
src/pyfaf/problemtypes/core.py
src/pyfaf/repos/__init__.py
src/pyfaf/repos/rpm_metadata.py
src/pyfaf/solutionfinders/__init__.py
src/pyfaf/solutionfinders/probable_fix_solution_finder.py
src/pyfaf/storage/report.py
src/pyfaf/ureport.py
src/pyfaf/utils/web.py
src/webfaf/blueprints/celery_tasks.py
src/webfaf/blueprints/symbol_transfer.py
src/webfaf/dumpdirs.py
src/webfaf/filters.py
src/webfaf/forms.py
src/webfaf/login.py
src/webfaf/problems.py
src/webfaf/reports.py
src/webfaf/utils.py

Inheriting method must have the same arguments and no else after return

---

pylintrc
src/webfaf/problems.py

pylint: Make refactoring limits less restricting

---

src/pyfaf/storage/migrations/versions/729a154b1609_index_reportpackages.py
src/pyfaf/storage/migrations/versions/Makefile.am

storage: Create index to speedup save-reports

---

src/pyfaf/actions/cleanup_packages.py
src/pyfaf/actions/cleanup_unassigned.py
src/pyfaf/actions/pull_reports.py
src/pyfaf/actions/reposync.py
src/pyfaf/actions/save_reports.py
src/pyfaf/actions/stats.py
src/pyfaf/celery_tasks/__init__.py
src/pyfaf/cmdline.py
src/pyfaf/common.py
src/pyfaf/problemtypes/kerneloops.py
src/pyfaf/queries.py
src/pyfaf/solutionfinders/__init__.py
src/pyfaf/storage/custom_types.py
src/pyfaf/storage/events.py
src/pyfaf/storage/events_fedmsg.py
src/pyfaf/storage/fixtures/__init__.py
src/pyfaf/utils/web.py
src/webfaf/blueprints/celery_tasks.py
src/webfaf/problems.py
src/webfaf/stats.py
src/webfaf/summary.py
src/webfaf/webfaf_main.py

Remove unused arguments and variables

---

src/webfaf/utils.py

db.session.delete() can delete either a Query object or only one object the query finds.

webfaf: Fix deletion of bugzilla comments and attachments

---

tests/actions
tests/faftests/__init__.py
tests/faftests/test_config.conf
tests/webfaf/Makefile.am
tests/webfaf/user

tests: Add unit tests for user actions

---

docker/Dockerfile

As I was building this image today it was broken. This commits fix it.

Docker changes

---

configure.ac

(commit message has the documentation)

do not disable maintainer mode (by default)

---

faf.spec.in
src/pyfaf/bugtrackers/mantisbt.py

mantisbt: Use zeep instead of suds

---

HACKING.md

Add HACKING.md

---

docker/Dockerfile_local

docker: Add vim into development image

---

HACKING.md

Fixes typographical errors in HACKING.md

Fixes typographical errors in HACKING.md

---

src/webfaf/dumpdirs.py
tests/test_webfaf/test_dumpdirs.py

Hello @marusak,
Following your help in the comments, I attempted this change to fix #592 . Please review. 
Thanks

Fixes #592 to accept archive filename with milliseconds.

---

HACKING.md

HACKING: Mention docker in building section

---

HACKING.md

HACKING: Include reporting part

---

Makefile.am

Makefile: Include README.rst

---

src/webfaf/dumpdirs.py

Fix issues with dumdirs

---

.copr/Makefile

Enable automatic build in copr

---

src/pyfaf/storage/migrations/versions/Makefile.am
src/pyfaf/storage/migrations/versions/a2b6d12819f9_drop_yum_type.py

Add migration script for dropping yum repo type

---

src/pyfaf/problemtypes/kerneloops.py

koops: Check if returned normalized list isnt empty

---

faf.spec.in
src/pyfaf/actions/Makefile.am
src/pyfaf/actions/__init__.py
src/pyfaf/actions/cleanup_packages.py
src/pyfaf/actions/cleanup_unassigned.py
src/pyfaf/actions/releasedel.py
src/pyfaf/queries.py
src/pyfaf/storage/migrations/versions/093be3eab7e9_add_ondelete_cascade_to_problem_tables.py
src/pyfaf/storage/migrations/versions/Makefile.am
src/pyfaf/storage/migrations/versions/cb084388e232_add_ondelete_cascade_to_report_bt_tables.py
src/pyfaf/storage/migrations/versions/e17dc14292b9_add_ondelete_cascade_to_report_tables.py
src/pyfaf/storage/problem.py
src/pyfaf/storage/report.py
tests/test_actions.py

Delete opsys release from db, including LOBs.
Beside OpSysRelease deletes also linked Bugzillas, Mantis Bugzillas, Repositories,
Reports, Problems and assigned Builds.

Implement new action releasedel

---

faf.spec.in
src/pyfaf/actions/__init__.py
src/pyfaf/bugtrackers/bugzilla.py
src/pyfaf/checker.py
src/pyfaf/common.py
src/pyfaf/storage/Makefile.am
src/pyfaf/storage/__init__.py
src/pyfaf/storage/bugtracker.py
src/pyfaf/storage/bugzilla.py
src/pyfaf/storage/debug.py
src/pyfaf/storage/externalfaf.py
src/pyfaf/storage/generic_table.py
src/pyfaf/storage/llvm.py
src/pyfaf/storage/mantisbt.py
src/pyfaf/storage/opsys.py
src/pyfaf/storage/problem.py
src/pyfaf/storage/project.py
src/pyfaf/storage/report.py
src/pyfaf/storage/sf_prefilter.py
src/pyfaf/storage/symbol.py
src/pyfaf/storage/task.py
src/pyfaf/storage/user.py
src/pyfaf/utils/web.py

Wasn’t too sure about `BzBug` and its instance attribute count. Should the global limit be bumped or is it better to silence the warning just there?

Apply some shut-up cream for pylint

---

src/webfaf/reports.py

Fixes https://github.com/abrt/faf/issues/589, please have a look at this.

Traceback during DB outage

---

src/pyfaf/queries.py
src/webfaf/reports.py
src/webfaf/templates/reports/item.html

Displays the version of the crashing package on the respective report's page.

Component version added to Reports page

---

config/plugins/centos.conf
src/pyfaf/opsys/centos.py
src/pyfaf/opsys/fedora.py

Keep supported CentOS versions in plugins/centos.conf

---

src/pyfaf/opsys/centos.py
src/pyfaf/opsys/fedora.py
src/pyfaf/storage/migrations/versions/8ac9b3343649_add_semver_semrel_to_.py
src/pyfaf/storage/migrations/versions/Makefile.am
src/pyfaf/storage/report.py
src/webfaf/problems.py
tests/test_mark_probably_fixed.py
tests/test_queries.py

Add semver and semrel columns to `reportunknownpackages` table, tweak tests, migrate DB with Alembic, add query to `problems.py`
Resolves #632

Add querying for unknown packages by semver and semrel

---

src/pyfaf/actions/cleanup_packages.py
src/pyfaf/queries.py
tests/test_actions.py

cleanup: Add option to delete packages by arch

---

src/pyfaf/storage/migrations/versions/fd5dc71471cc_set_pkg_name_to_256.py
src/pyfaf/storage/opsys.py
src/pyfaf/storage/report.py

Alter name column in packages table to varchar(256)

---

src/pyfaf/actions/retrace.py
src/pyfaf/retrace.py

This PR replaces parts of the RetraceWorker code that deal with:
- creating worker threads
- keeping track of ones that are alive
- moving tasks from queue to queue
with just three lines of code.
1) Create a ThreadPoolExecutor
2) Submit tasks to the executor
3) Add a callback for submitted tasks

retrace: Refactor the RetraceWorker

---

src/pyfaf/rpm.py

The rpm2cpio.wait() caused a deadlock when cpio failed with error
'Malformed number <bin>' and didn't exit.
Timeout should also help to prevent cpio getting stuck for too long.
https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait

rpm: Fix possible deadlock when unpacking rpms

---

pylintrc
src/pyfaf/actions/c2p.py
src/pyfaf/actions/create_problems.py
src/pyfaf/retrace.py
src/pyfaf/storage/custom_types.py
src/pyfaf/storage/jsontype.py

Fix/disable issues from Pylint 2.4, see http://pylint.pycqa.org/en/latest/whatsnew/2.4.html

Fix pylint issues for rawhide build

---

tests/test_rpm_metadata.py

Currently, the socket for the HTTP server is created when the thread
is started, requiring the following code to sleep for a bit. Even with
that, it seems that the test fails on COPR due to some requests being
refused. Not sure what exactly is going on, but smells like a timing
issue as well. This commit rewrites the test in a way that ensure that
the socket starts listening way before we start serving requests.

tests: rpm_metadata: Avoid races

---

HACKING.md

Just something I forgot about in PR #855 

Fix scheduler howto

---

HACKING.md

Clarify the usage of faf-celery-{worker,beat} services

---

src/pyfaf/storage/fixtures/__init__.py
src/pyfaf/storage/report.py
src/pyfaf/utils/storage.py
src/webfaf/templates/_helpers.html
src/webfaf/templates/reports/diff.html
tests/sample_reports/low_quality1

Problem types should be lowercase as defined in Satyr.

Fix case of problem types

---

src/webfaf/static/css/style.css
src/webfaf/static/js/custom.js
src/webfaf/templates/_helpers.html
src/webfaf/templates/problems/item.html
src/webfaf/templates/problems/list_table_rows.html
src/webfaf/templates/reports/item.html
src/webfaf/templates/reports/list_table_rows.html

See commits.
This mainly truncates the various strings displayed in the web UI. Some visuals incoming as well.

Truncate crash functions

---

lgtm.yml

lgtm: prepare worker for make

---

.copr/Makefile
README.md

Improvise. Adapt. Overcome.
Related: https://github.com/abrt/faf/pull/890

Remove old hook for copr build

---

tests/test_actions.py

One of the test cases uses a remote repository, but we can simply serve
a dummy one locally.
Fixes https://github.com/abrt/faf/issues/613

tests: test_actions: Do not require Internet access

---

src/pyfaf/bugtrackers/mantisbt.py

See commits.
Closes https://github.com/abrt/faf/issues/909

MantisBT fixes

---

src/pyfaf/actions/cleanup_packages.py
src/pyfaf/actions/reposync.py

See commits, not sure what the right approach here is.
Closes https://github.com/abrt/faf/issues/926

reposync: Re-download LOBs if missing

---

container/README.md

container/README: Update container path

---

src/pyfaf/storage/generic_table.py

generic_table: Remove redundant import

---

src/pyfaf/storage/generic_table.py
src/pyfaf/storage/migrations/versions/e1e54ec3137d_use_rpm_extension_with_lobs.py
src/pyfaf/storage/opsys.py

storage: Use file extensions with package LOBs

---

CHANGELOG.md
src/pyfaf/actions/check_repo.py
src/pyfaf/solutionfinders/prefilter_solution_finder.py
src/pyfaf/storage/problem.py
src/pyfaf/storage/report.py
src/webfaf/blueprints/celery_tasks.py
src/webfaf/reports.py
src/webfaf/webfaf_main.py
tests/test_actions.py
tests/test_webfaf/test_reports.py

Fix RHEL 8 builds

---

src/bin/faf

This should help with debugging in a lot of cases.

Dump backtrace on exception

---

.packit.yml

* Build via Packit on push to the master branch as well (in addition to build on PR).

Tweak Packit config

---

README.md

We have migrated from Freenode to Libera Chat.

readme: Update IRC channel

---

CHANGELOG.md
src/pyfaf/actions/assign_release_to_builds.py
src/pyfaf/actions/reposync.py
src/pyfaf/actions/retrace.py
src/pyfaf/bugtrackers/bugzilla.py
src/pyfaf/faf_rpm.py
src/pyfaf/opsys/fedora.py
src/pyfaf/retrace.py
src/pyfaf/storage/__init__.py
src/pyfaf/storage/opsys.py

Fix various code style issues: long lines, Pythonicity, type annotations, etc.
See commits for details.

Various code style fixes

---

src/pyfaf/actions/addcompathashes.py
src/pyfaf/actions/fedmsg_notify.py
src/pyfaf/actions/pull_reports.py
src/pyfaf/actions/sf_prefilter_soladd.py
src/pyfaf/opsys/centos.py
src/pyfaf/problemtypes/core.py
src/pyfaf/problemtypes/python.py
src/pyfaf/queries.py
src/pyfaf/retrace.py
src/pyfaf/solutionfinders/probable_fix_solution_finder.py
src/pyfaf/storage/fixtures/__init__.py
src/pyfaf/storage/problem.py
src/pyfaf/storage/report.py
src/pyfaf/ureport.py
src/pyfaf/ureport_compat.py
src/pyfaf/utils/web.py

I'm experimenting with SonarQube so here are a few fixes it's suggested - mostly needlessly nested conditions and some minor style issues.  
Also, one actual bug in a table definition in `storage`.

Sonar linting

---

HACKING.md

Signed-off-by: Michal Srb <michal@redhat.com>

[docs] Fix wiki link

---

src/pyfaf/storage/fixtures/__init__.py

Left over from https://github.com/abrt/faf/pull/1017.

Deduplicate code
