abrt/faf

src/pyfaf/problemtypes/core.py
src/pyfaf/problemtypes/java.py
src/pyfaf/problemtypes/kerneloops.py
src/pyfaf/problemtypes/python.py

Closes #357
This basically disables backtrace deduplication that never worked. A new backtrace will be created every time a report with a new ReportHash comes in (or an older report that has no backtrace).

pyfaf: always create new backtrace for report if it has none

---

src/webfaf2/hub.wsgi

Required for EL6 to use correct SQLAlchemy.
Semver PR should be merged first as it add correct Requires to spec.

webfaf2: require SQLAlchemy in hub.wsgi too

---

src/pyfaf/actions/c2p.py

Fixes RHBZ#1199509
Signed-off-by: Michal Toman <michal.toman@gmail.com>

c2p: do not die when eu-unstrip returns non-printable characters

---

src/webfaf2/filters.py
src/webfaf2/templates/_helpers.html
src/webfaf2/webfaf2_main.py

For users to have at least some information about the frame in
case retracing didn't succeed.
Closes #389

webfaf2: show frame addresses and build IDs

---

src/pyfaf/actions/create_problems.py
tests/create_problems
tests/faftests/__init__.py
tests/sample_reports/Makefile.am
tests/sample_reports/ureport_core1

Previously an old problem had to match in at least a half of
its reports to be reused. This methods reuses the old problem
if at least one report matches. Also properly connects the best
matches together.
This should reduce the number of empty problems left after a run
of create-problems.

pyfaf: better reuse old problems in create-problems

---

config/plugins/Makefile.am
config/plugins/fedmsg.conf
config/plugins/web2.conf
faf.spec.in
src/pyfaf/actions/Makefile.am
src/pyfaf/actions/fedmsg_notify.py
src/pyfaf/actions/stats.py
src/pyfaf/utils/web.py
src/webfaf2/webfaf2_main.py
tests/faftests/test_config.conf

Fedmsg based notifications
Related:
https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/pull/259
https://github.com/fedora-infra/fmn.rules/pull/48

Fedmsg notify

---

src/pyfaf/actions/retrace.py
src/pyfaf/problemtypes/__init__.py
src/pyfaf/problemtypes/core.py
src/pyfaf/problemtypes/java.py
src/pyfaf/problemtypes/kerneloops.py
src/pyfaf/problemtypes/python.py
src/pyfaf/problemtypes/ruby.py
src/pyfaf/storage/migrations/versions/48550f308625_add_symbolsource_retrace_fail_count.py
src/pyfaf/storage/migrations/versions/Makefile.am
src/pyfaf/storage/symbol.py

This option allows to stop retracing a symbol after a given count of failed runs. In the production DB there are many symbols that fail over and over and eat the majority of processing time. The action should still be run occasionally without this option to to retry retracing of all symbols.

pyfaf: add retrace --max-fail-count

---

config/plugins/fedmsg.conf
faf.spec.in
src/pyfaf/storage/Makefile.am
src/pyfaf/storage/__init__.py
src/pyfaf/storage/events_fedmsg.py
src/pyfaf/storage/report.py

The plugins adds a "set" handler on Report.count. Whenever the
count goes over one of the thresholds, a fedmsg notification is
sent immediately.
If the package is not installed or disables in configuration,
there is zero overhead in report saving.

pyfaf: realtime fedmsg notifications

---

src/webfaf2/templates/base.html

With this change, we are adding on the bottom right side of the screen
a small menu, specific to Fedora that provides a way for Fedora users
to quickly navigate through our applications.

Add fedmenu but display it only if configured for FAF

---

src/pyfaf/actions/pull_reports.py

The pull-reports action uses pickle to save the set of already pulled reports
to avoid pulling duplicated. Since the pickle can grow in size a lot, it can
take a couple of seconds to save to the disk. This change makes the pickle to
be saved only once after pulling all the reports instead of saving it after
every single pull. This significantly improves the speed of pulling.

pyfaf: pickle saved report ids only once in pull-reports

---

src/pyfaf/actions/update_bugs.py
src/pyfaf/bugtrackers/mantisbt.py

Related to the fact that MantisBT bugs' IDs are stored in the `external_id`
field not `id` as it is the case with Bugzilla bugs.
Related to #411

pyfaf: fix update-bugs for MantisBT

---

src/webfaf2/reports.py
tests/webfaf/reports

`commit` must be used insted of `flush` to save the DB session
inside a web request.

webfaf2: fix saving of invalid uReports

---

src/webfaf2/templates/problems/item.html

This way people will use permalinks instead of urls with
ever-changing problem IDs when copy-pasting the url somewhere.
See https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Manipulating_the_browser_history

webfaf2: replace problem.item url with permalink in browser url bar

---

src/pyfaf/bugtrackers/__init__.py
src/pyfaf/bugtrackers/bugzilla.py
src/pyfaf/bugtrackers/mantisbt.py
src/pyfaf/storage/report.py

Bugtracker plugins are no longer hardcoded and show automatically
in report.item and problem.item and list.

pyfaf: load Report bug backrefs based of bugtracker plugins

---

src/pyfaf/bugtrackers/bugzilla.py

Our service is crashing with the following exception:
```
DEBUG:urllib3.connectionpool:"POST /xmlrpc.cgi HTTP/1.1" 200 None
Traceback (most recent call last):
File "/usr/bin/faf-save-reports", line 92, in <module>
bugzilla.login()
File "/usr/lib/python2.6/site-packages/pyfaf/bugzilla.py", line 61, in login
self.bz.login(user, password)
File "/usr/lib/python2.6/site-packages/bugzilla/base.py", line 639, in login
ret = self._login(self.user, self.password)
File "/usr/lib/python2.6/site-packages/bugzilla/base.py", line 607, in _login
return self._proxy.User.login({'login': user, 'password': password})
File "/usr/lib64/python2.6/xmlrpclib.py", line 1199, in __call__
return self.__send(self.__name, args)
File "/usr/lib/python2.6/site-packages/bugzilla/base.py", line 169, in …
```

bugzilla: don't use tokenfile

---

config/faf.conf.in
src/pyfaf/actions/addcompathashes.py
src/pyfaf/actions/attach_centos_bugs.py
src/pyfaf/queries.py
src/pyfaf/solutionfinders/__init__.py
src/pyfaf/ureport.py
src/webfaf/blueprints/symbol_transfer.py
src/webfaf/problems.py
src/webfaf/reports.py
tests/faftests/__init__.py
tests/faftests/test_config.conf
tests/sample_reports/Makefile.am
tests/sample_reports/ureport_duplicate
tests/sample_reports/ureport_duplicate2
tests/sample_reports/ureport_duplicate3
tests/sample_reports/ureport_duplicate4
tests/webfaf/reports

https://github.com/abrt/faf/issues/489
Add known option to faf's configure file, renamed and rework method 'get_report_by_hash'
to 'get_report' which can finding known reports by OS attributes like OS Major version,
OS Minor version, OS architecture, next added method is 'get_reportbz_by_major_version'
which is searching bugzilla report's by OS Major version.
I added tests for all possible cases.

Configurable finding known ureport and buzilla bug's

---

src/webfaf/blueprints/celery_tasks.py

In Python 2.6 was syntax error.

Syntax error in celery task action filter

---

src/pyfaf/ureport.py

Currently, a single URL can be added to the database only once - in other words, it is not possible to attache a single URL to more micro reports. I was not able to find a justification for it.
We have found a use case where we need to attach a single URL to more micro reports (test case URL). So this commit removes the constraints of uniqueness of URL column which is enforced in the application logic.
The constraint is enforced by looking up for the url in the reporturls. The commit adds a new filter condition which will ensure that a single URL can be attached to more micro reports but just only once to a particular one.

Attachments: One url can be attached to many reports

---

src/webfaf/reports.py

Remove debug print when creating new bug for a report

---

src/pyfaf/problemtypes/core.py
src/pyfaf/problemtypes/kerneloops.py

The tool requires hexadecimal address. The address must be converted to
int first to avoid the "L" suffix as the type of address is long. int
and long are unified for a quite long while so it safe to cast long to
int.
Signed-off-by: Jakub Filak <jfilak@redhat.com>

retracing: execute eu-addr2line with hex address

---

src/pyfaf/utils/parse.py

Rationale: Always explicitly choose the canonical signal name where
multiple names match one signal number. For example always use SIGABRT
as canonical name and not its obscure SIGIOT alias.

pyfaf: use static dictionary for signal name

---

src/pyfaf/problemtypes/java.py

For the same reason we do not check format of C++ function names, it is
too complex.
Signed-off-by: Jakub Filak <jfilak@redhat.com>

java: drop all requirements on frame name

---

src/pyfaf/ureport.py

The removed command is clearly a bug. There is no need to load all
micro-reports and the variable is never used.
Signed-off-by: Jakub Filak <jfilak@redhat.com>

ureport: stop wasting memory by loading all ureports

---

tests/bin/eu-addr2line

RHEL-6 was not subject of the /usr move.
Signed-off-by: Jakub Filak <jfilak@redhat.com>

retrace: fix tests failing on RHEL6

---

faf.spec.in
src/pyfaf/actions/Makefile.am
src/pyfaf/actions/assign_release_to_builds.py
src/pyfaf/actions/cleanup_packages.py
src/pyfaf/actions/repoassign.py
src/pyfaf/actions/reposync.py
src/pyfaf/opsys/fedora.py
src/pyfaf/queries.py
src/pyfaf/storage/migrations/versions/133991a89da4_build_to_opsysrelease.py
src/pyfaf/storage/migrations/versions/17d4911132f8_assigning_release_to_repo.py
src/pyfaf/storage/migrations/versions/Makefile.am
src/pyfaf/storage/opsys.py
tests/actions
tests/faftests/__init__.py

We need to be able get all package of a single release to perform efficient garbage collection of packages/builds of EOL releases. Now it is not possible to get all builds that belong to a specific operating system release because there is no relationship between operating system releases and builds. To make this possible we must introduce a new link table that will connect Builds, OpSysRelease and Arch. Having this link table would also solve another problem and that is need to be able to create a yum repository from all builds of a single release of operating system in order to be able to install a minimal set of packages to prepare a chroot environment for backtrace generation. 
The table will be populated in the “reposync” action. The action iterates over all packages in a repository …

Add old package garbage collector

---

src/pyfaf/actions/reposync.py

The implementation did not consider that there could be two packages, that
differ only in architecture. This is usual for libraries.
For example:
$ls /valid/repo | grep libselinux
>libselinux-2.5-9.fc24.i686.rpm
>libselinux-2.5-9.fc24.x86_64.rpm
Both packages come from the same build. When the first one is processed, new
build (if not in database yet) is added into database and is linked with
architecture from package. When the second package is processed, build already
exists and therefore no link is added.
This commit fixes this behaviour by always checking, whether the specific link
exists or not.

Fix creating link between build and architecture

---

src/pyfaf/queries.py

Selecting packages did not considered using architecture and selected all
architectures.

Use also architecture when selecting packages

---

src/pyfaf/queries.py

The problem is that Arch is in Build as well as in BuildOpSysReleaseArch.
Join therefore could not be created and ProgrammingError was returned.

queries: fix wrong join

---

src/pyfaf/storage/migrations/versions/183a15e52a4f_report_history_unique.py

In the commit e88e67d a new migration script was added but its downversion did
not point to the current head. That meant that there were two heads.
Before this commit:
$alembic heads
>133991a89da4 (head)
>183a15e52a4f (head)
After this commit:
$alembic heads
>183a15e52a4f (head)

pyfaf: Fix revision tree

---

faf.spec.in
tests/Makefile.am
tests/alembic

Introduce test for testing if there is only one head for alembic tree.
Creating new revision automatically sets down version to the current head. But
if in the time of creating author does not have current head, or the head
changes in the time between creating revision and merging the code, it can
create new head, which is not intended.

tests: Add test for alembic migration tool

---

src/bin/faf-migrate-db

There was easy way how to move database to newer version, but no easy way how
to move to older version in case that something gets wrong.

pyfaf: Add option to downgrade database

---

configure.ac
src/pyfaf/actions/repoadd.py
src/pyfaf/actions/repoassign.py
src/pyfaf/actions/repodel.py
src/pyfaf/actions/repoimport.py
src/pyfaf/actions/repoinfo.py
src/pyfaf/actions/repolist.py
src/pyfaf/actions/repomod.py
src/pyfaf/actions/reposync.py
src/pyfaf/repos/yum.py
src/pyfaf/storage/migrations/versions/1c4d6317721a_support_mirrors.py
src/pyfaf/storage/migrations/versions/Makefile.am
src/pyfaf/storage/opsys.py
tests/Makefile.am
tests/actions
tests/sample_repo/Makefile.am
tests/sample_repo/dummy_repo.repo

This pull-request enables repositories to have more than one url, so in case that
one url is not available in time of reposyncing, another can be used.

Support mirrors

---

src/webfaf/static/js/report_graph.js

On summary page, when displaying by week, only year was displayed.
After this patch, instead the year, a month name and day is displayed.
Fixes #550
Before:
https://pageshot.net/Wo2Y8UzwucKyXR9K/localhost
After:
https://pageshot.net/9uYsVEAsKEIeYUeS/localhost

webfaf: Show month and day when weekly resolution

---

src/webfaf/reports.py
src/webfaf/templates/reports/item.html

If stack trace does not include main, it is hard to guess what
executable actually crashed. After this commit, executable is always
displayed.
Fixes #524

webfaf: Always show executable on report page

---

faf.spec.in
src/pyfaf/actions/Makefile.am
src/pyfaf/actions/delete_invalid_ureports.py
tests/actions

Action for deleting old invalid ureports. Takes one optional argument --age, when given deletes older invalid ureports than age. Without argument, deletes all invalid ureports.

Action delete invalid ureports

---

faf.spec.in
src/pyfaf/actions/Makefile.am
src/pyfaf/actions/cleanup_unassigned.py
tests/actions

In commit 8b9bcac was introduced assigning releases to build. Also in
a6b9ba4 was introduced cleaning of builds (packages) for specific
assigned release. However, unassigned builds cannot be removed.
This commit introduces action for cleaning such builds (packages). Since
I understand this is rather a dangerous action, I made it run by default
as dry run and only by using `--force` packages can be removed.

pyfaf: Add action for deleting all unassigned builds

---

src/pyfaf/actions/assign_release_to_builds.py

if we do not commit after each package it is ~1000x faster

speed up assign_release_to_builds

---

config/plugins/save-reports.conf
src/pyfaf/actions/save_reports.py

Allows user to configure if ureports of new, yet unknown components,
that means those not yet present in database, should be stored as well.
Default value is false, as it was the only behavior yet.

save-reports: saving unkonwn components configurable

---

config/plugins/web.conf
src/pyfaf/utils/web.py

URLs attached into FedMsg notifications were always prefixed
by 'http://' even the server runs over https.
The URL prefix is now controlled by a new option 'require_https' which
was added into 'web.conf'. If the option is 'true' URLs are prefixed
by 'https://'.
Fixes #564
Signed-off-by: Matej Habrnal <mhabrnal@redhat.com>

Fix url to FAF report in FedMsg notification

---

src/pyfaf/actions/reposync.py
tests/actions

Reposync firstly checks all repositories, and only if all repositories
are ready and correct downloading starts. That means that if only one
incorrect repository is present, no repository is reposynced, even
though there are correct and available ones.

reposync: Do not exit when cannot process one repo

---

src/webfaf/dumpdirs.py
tests/webfaf/dumpdirs

Submitting dumpdir archive expects the first part of filename (the type)
to consist only from small letters.
However the type can be Python or Python3. These filenames were
rejected.
This commit fixes this. Now name can be Python3 (see the updated test).

webfaf: Dumpdirs support for more filenames

---

pylintrc

80 is soo oldies. most terms nowdays are capable to show 120 chars.

pylint: allow 120 chars on line

---

src/pyfaf/actions/stats.py
src/webfaf/blueprints/celery_tasks.py
src/webfaf/blueprints/symbol_transfer.py
src/webfaf/dumpdirs.py
src/webfaf/forms.py
src/webfaf/problems.py
src/webfaf/reports.py
src/webfaf/stats.py
src/webfaf/templates/base.html

Modules reports, problems and dumpdirs contain functions called `list()`. I don't consider redefinition of Python's built-in functions to be a good practice. This can cause an errors that are really hard to debug. I suggest to rename these functions. In my opinion the name "dashboard" reflects the data content of documents on routes /problems and /reports.

webfaf: remove redefinitions of built-in list function

---

src/webfaf/templates/dumpdirs/new.html

Users can get confused when gnome abrt sends them to this page.
This commit introduces some short explanation to help understand users
what has happened and how can they proceed.
Somewhat related to https://github.com/abrt/faf/issues/547
If somebody has better idea what to write there or how it should look like, let me know and I'll gladly change it:)

webfaf: Explain dumpdirs

---

docker/Dockerfile
docker/Dockerfile_local
docker/Makefile
docker/README.md
docker/files/crontab-faf
docker/files/init_db

Obsoletes abrt/faf-docker repository.
Why have I created a new docker image?
Firstly, because I didn't know there is one.
Secondly, the image needed some rewriting and rethinking.
So why is it directly in FAF repo?
Because it is the correct place. We do not need another repository for
so little data. And also, nobody misses it ever again:)
How does it differ?
The biggest difference is that it builds FAF from currently checked out
git branch. It makes it perfect for development. It makes however, the image a
bit bigger (there are some build-requires).

docker: Introduce FAF docker image

---

src/pyfaf/storage/migrations/versions/acd3d9bf85d1_ignore_private_bz.py

you cannot add column with nullable=False without default. DB will error that the column contains nullable values

fix migration - ignore_private_bz

---

docker/files/run_faf

These changes allow to run FAF in OpenShift with database and FAF's data saved on persistent volume, and deployment on multiple pods.

docker: Improve run_faf script for openshift

---

src/pyfaf/solutionfinders/__init__.py
src/pyfaf/solutionfinders/prefilter_solution_finder.py
src/pyfaf/solutionfinders/probable_fix_solution_finder.py
src/pyfaf/ureport.py
src/webfaf/reports.py

1) Because it is better to know, if the ureport is valid
2) It has side effects (edits the ureport)
Closes #501

ureport: Always check for validity of ureport

---

docker/Dockerfile_local

Since f248784f5ebaf3a6e39eb3d5ca1d749f0b8ef556 rpmspec is needed to get list of dependencies with "autogen.sh sysdeps".
eval helps with evaluation of "package >= 0.00" strings.

docker: fix issue with autogen and rpmspec

---

config/plugins/web.conf
faf.spec.in
src/webfaf/config.py
src/webfaf/webfaf_main.py

Limits the rate at which the messages are passed to the SMTP handler.
It uses a token bucket based algorithm to filter the messages.
* Ex.1: rate=1 timeframe=30 burst=1
After a mail is sent there is a 30s period until another one can be sent.
* Ex.2: rate=1 timeframe=60 burst=5
Allows to send 5 mails in burst before the filtering kicks in. After that
the number of mails that can be sent starts recovering at the rate of 1 mail
per 60s.
There is also possibility to filter the mails based on the substring
in the exception message.
More info at https://github.com/wkeeling/ratelimitingfilter

WIP webfaf: Limit the number of exception mails

---

src/pyfaf/repos/rpm_metadata.py

In Python 2, `StandardError` was the base class for all built-in exceptions
other than `StopIteration`, `GeneratorExit`, `KeyboardInterrupt`, and `SystemExit`.
In Python 3, `StandardError` has been eliminated; use `Exception` instead.

py3compatibility: StandardError

---

src/pyfaf/actions/mark_probably_fixed.py
src/pyfaf/actions/stats.py
src/pyfaf/storage/fixtures/randutils.py
src/webfaf/filters.py

Support of the same "classic" division in both Python 2 & 3 simultaneously.
It is related to such a division when both operators are ```int```.

py3 compatibility: classic division - corrected

---

src/webfaf/dumpdirs.py

When opening a file, it is preferable to use `open()`
instead of invoking the `file` constructor directly.
`file()` has been removed in Python 3.

py3 compatibility: file

---

src/pyfaf/actions/create_problems.py

The new literal syntax for sets is available and preferred in Python 3.
It has been backported to Python 2.7.

py3 compatibility: Set literals

---

src/pyfaf/utils/format.py

`reduce()` was removed from built-ins in Python 3 and has been placed
into `functools` module since Python 2.6 to allow writing code
more forward-compatible with Python 3.

py3 compatibility: Add `from functools import reduce`

---

src/pyfaf/actions/stats.py

Python 2 had separate `int` and `long` types for non-floating-point numbers.
In Python 3, there is only `int` type, which mostly behaves like
the `long` type in Python 2. The replacement of `long` with `int` type
should not have any impact in Python 2 as the value is related to days here.

py3 compatibility: Replacement of long type with int type

---

src/pyfaf/storage/fixtures/__init__.py
src/pyfaf/utils/decorators.py

`isinstance` built-in function is preferred to compare types.

py3 compatibility: Replacement of type()== with isinstance()

---

src/pyfaf/actions/mark_probably_fixed.py
src/pyfaf/actions/pull_components.py
src/pyfaf/queries.py
src/pyfaf/utils/format.py

Replacement of `lambda (a, b): function(a, b)`
with `lambda a_b: function(a_b[0], a_b[1])` according to PEP 3113.

py3 compatibility: Removal of tuple parameter unpacking

---

src/pyfaf/utils/contextmanager.py
src/webfaf/dumpdirs.py
tests/alembic
tests/webfaf/dumpdirs
tests/webfaf/reports

The `StringIO` and `cStringIO` modules are gone in Python 3.
Instead, import the `io` module and use `io.StringIO` or `io.BytesIO`
for text and data respectively.

py3 compatibility: Replace StringIO and cStringIO modules with io module

---

faf.spec.in
src/pyfaf/storage/__init__.py
src/webfaf/forms.py
src/webfaf/stats.py

The `unicode` type is `unicode` in Python 2 and `str` on Python 3.
The replacement of `unicode` type with `six.text_type` ensures
the compatibility between Python 2 and Python 3.

py3 compatibility: Replacement of `unicode` type with `six.text_type`

---

src/pyfaf/actions/retrace.py
src/pyfaf/actions/retrace_remote.py
src/pyfaf/retrace.py
src/pyfaf/storage/__init__.py
src/webfaf/utils.py

In Python 2, `range()` returns a list, and `xrange()` returns an iterator.
In Python 3, `range()` returns an iterator, and `xrange()` doesn’t exist.
The compatibility is solved by six library.

py3 compatibility: Replacement of xrange with six.moves.range

---

src/pyfaf/utils/format.py

In Python 2, the global `zip()` function took any number of sequences
and returned a list of tuples. In Python 3, `zip()` returns an iterator
instead of a list.

py3 compatibility: Replacement of zip with six.moves.zip

---

src/pyfaf/actions/c2p.py
src/pyfaf/bugtrackers/bugzilla.py
src/pyfaf/opsys/fedora.py
src/pyfaf/repos/yum.py

`basestring` is an abstract type in Python 2, a superclass for both
`str` and `unicode` string types. In Python 3, there is only one
string type of `str`. The compatibility is solved by six library.

py3 compatibility: Replacement of basestring with six.string_types

---

src/pyfaf/actions/pull_reports.py
src/pyfaf/problemtypes/kerneloops.py

The `cPickle` and `pickle` modules of Python 2 were merged in `pickle` module in Python 3.

py3 compatibility: Replace cPickle module with pickle module

---

src/pyfaf/actions/repoimport.py
src/pyfaf/config.py

The `ConfigParser` module of Python 2 is renamed to `configparser` in Python 3.

py3 compatibility: Replace ConfigParser module with configparser

---

src/webfaf/templates/_helpers.html

I noticed the lack of this, because I tried pasting the "invalid" HTML thru the jekyll blog engine.
Jekyll's markdown parser caused the entire table content to be hidden.
(This happens because jekyll ends up escaping the final `</table>`).

 webfaf: add omitted </td> in backtrace table

---

src/pyfaf/actions/retrace.py
tests/rpm_metadata

The `Queue` module of Python 2 was renamed to `queue` module in Python 3.

py3 compatibility: Replace Queue module with queue module

---

src/pyfaf/actions/create_problems.py

`six.itervalues()` replaces `dictionary.itervalues()` on Python 2
and `dictionary.values()` on Python 3.

py3 compatibility: Replacement of itervalues with six.itervalues

---

src/pyfaf/utils/storage.py
src/webfaf/blueprints/celery_tasks.py

`six.iteritems()` replaces `dictionary.iteritems()` on Python 2
and `dictionary.items()` on Python 3.

py3 compatibility: Replacement of iteritems with six.iteritems

---

src/pyfaf/actions/stats.py
src/pyfaf/config.py
src/pyfaf/problemtypes/kerneloops.py
src/pyfaf/solutionfinders/__init__.py
src/pyfaf/storage/opsys.py

In Python 2, `filter(function, iterable)` returns a list and is equivalent
to `[item for item in iterable if function(item)]` if function is not `None`
and `[item for item in iterable if item]` if function is `None`. In Python 3,
the function returns an iterator. The replacement of Python 2 `filter`
function with a proper equivalent solves the Python 3 compatibility.

py3 compatibility: Replace filter function with a list equivalent

---

src/pyfaf/__init__.py
src/pyfaf/storage/__init__.py
src/pyfaf/storage/opsys.py
src/webfaf/dumpdirs.py
src/webfaf/forms.py
src/webfaf/hub.wsgi
src/webfaf/login.py
src/webfaf/problems.py
src/webfaf/reports.py
src/webfaf/stats.py
src/webfaf/summary.py
src/webfaf/webfaf_main.py
tests/sample_plugin_dir/_noplugin.py
tests/sample_plugin_dir/plugin.py
tests/webfaf/webfaftests/__init__.py

In Python 3, imports can be either absolute or explicitly relative;
implicit relative imports are forbidden.

py3 compatibility: Adjust imports

---

src/pyfaf/storage/fixtures/data.py
src/pyfaf/storage/problem.py
src/pyfaf/utils/format.py
src/pyfaf/utils/proc.py
src/webfaf/config.py
src/webfaf/forms.py

`map()` built-in function returns a list on Python 2, but an iterator
on Python 3. In some context, the problem is solved by adding the `list()`
function. If the first argument to `map()` is a lambda function, then it
is converted to an equivalent list comprehension.

py3 compatibility: Ensure map function to return a list

---

Makefile.am

so it can be actually used during buildtime

add pylintrc to tar.gz

---

pylintrc
src/pyfaf/actions/hash_paths.py
src/pyfaf/opsys/centos.py
src/pyfaf/opsys/fedora.py
src/pyfaf/ureport.py
src/webfaf/reports.py

Removal of needless parentheses according to `pylint`.

Refactoring: Remove superfluous parens

---

faf.spec.in

1. `packagedb-cli` is deleted as it has not been required since https://github.com/abrt/faf/commit/4e56c268e3bc51d8b880393e400e8968de1ae76c
2. `%{satyr_dep}` replaces `satyr-python >= 0.9` at line 191 as it should be since https://github.com/abrt/faf/commit/b62cd1c23453cfa77215faa00e7ecff8e57f6368
3. Comment correction at line 734

Refactoring: spec file

---

src/pyfaf/actions/pull_reports.py

In python2 version of uuid there is method `get_hex()` as well as
property `hex` which do the same. In python3 version the method was
removed.

pull_reports: Update method name

---

src/pyfaf/bugtrackers/bugzilla.py

```
try:
raise Exception("ABC")
except Exception as e:
print(e)
print(e.message)
```
In python2 the above code prints:
```
ABC
ABC
```
but in python3 it prints:
```
ABC   <---------------- print(e)
Traceback (most recent call last):
File "<stdin>", line 2, in <module>
Exception: ABC
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<stdin>", line 5, in <module>
AttributeError: 'Exception' object has no attribute 'message'
```

py3: Exception does not have message member

---

src/pyfaf/actions/save_reports.py
tests/save_reports

This may be helpful when there is way to many reports to process. `--speedup` takes way too long to lock files and also only one process works on saving.

save-reports: Enable matching reports to save

---

config/faf.conf.in
config/plugins/fedmsg.conf
docs/fixture_notes
faf.spec.in
src/pyfaf/actions/__init__.py
src/pyfaf/actions/assign_release_to_builds.py
src/pyfaf/actions/create_problems.py
src/pyfaf/actions/reposync.py
src/pyfaf/bugtrackers/bugzilla.py
src/pyfaf/common.py
src/pyfaf/queries.py
src/pyfaf/solutionfinders/probable_fix_solution_finder.py
src/pyfaf/storage/__init__.py
src/pyfaf/storage/fixtures/__init__.py
src/pyfaf/utils/decorators.py
src/pyfaf/utils/storage.py
src/webfaf/dumpdirs.py
src/webfaf/reports.py
src/webfaf/stats.py
src/webfaf/templates/dumpdirs/new.html
src/webfaf/templates/problems/item.html
src/webfaf/templates/problems/problems_table.html
tests/checker
tests/create_problems
tests/faftests/__init__.py
tests/utils
tests/webfaf/reports

Hi @marusak,
I fixed some [codespell](https://github.com/codespell-project/codespell) issues. See,
```
$ codespell --skip="./src/webfaf/static/*,./.git*,*llvm.py,*sample-1.0-1.fc18.noarch.rpm"
```
You could be checking this in a CI, like CircleCI, [see](https://github.com/grafana/grafana/blob/master/.circleci/config.yml). Thanks!

Fix codespell issues

---

src/webfaf/config.py

The options from config file are strings, therefore they need to be converted
to integers.

webfaf: Pass ratelimiter only int values from config

---

src/pyfaf/checker.py

checker: Basestring not present in Python3

---

src/bin/faf
src/pyfaf/solutionfinders/prefilter_solution_finder.py
src/pyfaf/storage/__init__.py
src/pyfaf/utils/web.py

The 'warning' method is functionally identical to deprecated 'warn' method.
https://docs.python.org/3/library/logging.html#logging.Logger.warning

Replace deprecated warn method with warning method

---

faf.spec.in

The database server is not really needed by FAF, as the database may run
somewhere else and FAF only connects to it.

spec: Drop requirement on postgresql-server

---

config/faf

otherwise it emits warning and will not logrotate the files

tell logrotate to rotate files under faf:faf

---

faf.spec.in

The database server is not really needed by FAF, as the database may run
somewhere else and FAF only connects to it.
Continuation of 710821b

spec: Drop requirement on pg-semver

---

docker/Makefile

We release our images under abrt/ organization on dockerhub.
Building with this prefix make it weird to use, as there are different
names for build and for released images.
For example `make run` worked only with build image, but could not find
the released image.

docker: Tag build images

---

src/pyfaf/bugtrackers/bugzilla.py
src/webfaf/reports.py
tests/test_bugzilla.py

When an error occurs while associating a report to a bug, the flash message is very generic and the actual message is written to the server logs.
This patch will send the error message upstream along with adding it to the server logs.
Resolves: #710 
I am very much doubtful about the tests. Kindly let me improve on your suggestions. 
Thanks for the help throughout.

Fixes 710 : Display report-bug association error message

---

src/pyfaf/actions/reposync.py

This commit introduces way how to pick only specific repositories to be
reposynced.
For example, if there are repositories with following names:
fedora-29-x86_64
fedora-29-i386
fedora-27-x86_64
fedora-27-i386
fedora-29-updates-x86_64
fedora-29-updates-i386
fedora-27-updates-x86_64
fedora-27-updates-i386
And only want to reposync all repositories for fedora-29 run
`reposync --match-repo fedora-29`

reposync: Enable matching repositories by name

---

src/pyfaf/storage/opsys.py

Fixes abrt/faf#722
In Python3 comparing unorderable types rises TypeError.

storage: Make OpSysReleases orderable

---

faf.spec.in

Fix of issue #721 when after uninstallation, faf leaves behind
`__pycache__` directories.
Signed-off-by: Jan Beran <jberan@localhost.localdomain>

spec: fix of unowned __pycache__ directories

---

config/plugins/fedmsg.conf
configure.ac
faf.spec.in
src/Makefile.am
src/pyfaf/actions/fedmsg_notify.py
src/pyfaf/storage/events_fedmsg.py
src/schema/Makefile.am
src/schema/README
src/schema/faf_schema/__init__.py
src/schema/faf_schema/schema.py
src/schema/faf_schema/tests/__init__.py
src/schema/faf_schema/tests/test_schema.py
src/schema/setup.cfg
src/schema/setup.py

Adds `faf-schema` subpackage that defines message schema for the `fedora-messaging`
infrastructure. The `fedora-messaging` library is designed to be a replacement for
the `fedmsg` library.
Message schema should be treated as immutable. Once defined, they should not be altered. 
Instead, define a new schema class, mark the old one as deprecated, and remove it after an appropriate transition period.[1]
Docs:
[1] fedora-messaging.readthedocs.io/en/latest/messages.html#schema-are-immutable
fedora-messaging.readthedocs.io/en/latest/publishing.html
fedora-messaging.readthedocs.io/en/latest/tutorial/conversion.html

Define message schema and move to fedora-messaging from fedmsg

---

config/faf

Only log rotate *.log files, otherwise this will happen:
save-reports.log.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.gz.1.1

logrotate: Improvements to logrotate config

---

src/webfaf/reports.py

The 'os' argument was renamed to 'opsys' in 88d75024267c97bda926f347e875337d49282beb.
Fixes #742

reports: Fix endpoint for get_hash route

---

src/webfaf/static/css/style.css

Follow-up to revert 92965c1252a61565e3cdd807195d9875cd577e7f.
We didn't revert all changes made to styles, which caused some visual bugs.

webfaf: Remove residual css styles

---

src/pyfaf/actions/pull_reports.py

__init__() of the action is run always - even when you do not run the action itself, but some other
since load_known() loads pickle, which can be 100 MB, the memory structure can grow to up to 4 GB, which is wasting of
memory, when we actually do not need the data.

defer loading pickle of known pulled reports in pull_reports

---

src/webfaf/dumpdirs.py

This is fixes following error, where gzip's magic number is 0x1f 0x8b.
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

dumpdirs: Use bytes for rw operations on gzipped files

---

src/webfaf/templates/dumpdirs/new.html

I was working on some different issue and someone posted screenshot of this page and first thing I have noticed was "belowe"

dumpdir: Fix spelling issues

---

src/pyfaf/retrace.py

Strings were printed out as hex characters (ie. f = \x66).

retrace: Decode output of popen

---

src/webfaf/dumpdirs.py

If a dumpdir is sent to 'retrace.fp.org/faf/dumpdirs/new/xyz.tar' the server returns 
'301 MOVED PERMANENTLY'
and the request is redirected to 'retrace.fp.org/faf/dumpdirs/new/xyz.tar/' (see [1]).
This causes Flask to not process the upload instead return FormDataRoutingRedirect error.
When 'strict_slashes' are disabled the redirect is not triggered.
[1] http://werkzeug.pocoo.org/docs/0.14/routing/#rule-format

dumpdirs: Modify a route to accept uploads of dumpdirs

---

src/pyfaf/actions/fedmsg_notify.py
src/pyfaf/problemtypes/core.py
src/pyfaf/problemtypes/kerneloops.py
src/pyfaf/queries.py
src/webfaf/problems.py
src/webfaf/reports.py

Using the Python's 'is' operator to compare the columns to NULL produced wrong queries.
Instead the sqlalchemy defined 'is_' and 'isnot' functions should be used to do the
comparisons.
In some cases this also required to use real column names from tables.
ie.: opsys to opsys_id
See:
https://docs.sqlalchemy.org/en/latest/core/sqlelement.html#sqlalchemy.sql.operators.ColumnOperators.is_
https://docs.sqlalchemy.org/en/latest/core/sqlelement.html#sqlalchemy.sql.operators.ColumnOperators.isnot

queries: Use is_/isnot for None comparisons

---

src/webfaf/utils.py

Fixes:
TypeError: object of type 'generator' has no len()
Traceback (most recent call last):
File "/usr/lib64/python3.7/urllib/parse.py", line 873, in urlencode
if len(query) and not isinstance(query[0], tuple):
TypeError: object of type 'generator' has no len()
...
TypeError: not a valid non-string sequence or mapping object

webfaf:utils: Convert generator object to list

---

src/pyfaf/actions/c2p.py
src/pyfaf/retrace.py
src/pyfaf/utils/proc.py

If encoding is specified the file objects stdin, stdout and stderr will be opened
in text mode using the encoding specified in the call.
Should have changed it in https://github.com/abrt/faf/pull/751 already.

proc: Allow to specify encoding for *popen functions

---

src/pyfaf/problemtypes/core.py

I don't know what can cause this but the check should prevent from errors
when the unpacked_path variable stays None.

core: Check if unpacked binary path is defined

---

src/pyfaf/opsys/centos.py
src/pyfaf/opsys/fedora.py

According to new Versioning Guidelines [1], 'Version' can now include tilde(~) character.
[1] https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/#_versioning_prereleases_with_tilde

opsys: Add tilde to allowed chars in Version

---

src/pyfaf/actions/fedmsg_notify.py
src/pyfaf/storage/events_fedmsg.py

Validator from faf messaging schema requires component names to be a list of string values.
https://github.com/abrt/faf/blob/8b9a3444273fcc4476eec01baf808098c3637084/src/schema/faf_schema/schema.py#L58

fedmsg: Convert components names to list

---

tests/test_actions.py

Without it, the messages in assertions will never be shown:
https://github.com/rpm-software-management/createrepo_c/commit/4c2f4f48f259c19219d4d640884c5df7a7d4fc5e

tests: actions: Pass --verbose to createrepo

---

pylintrc
src/pyfaf/actions/fedmsg_notify.py
src/pyfaf/queries.py
src/webfaf/blueprints/symbol_transfer.py
src/webfaf/problems.py

First issue is with ambiguity of JOINs. That is, the JOIN would implicitly be against the first entity that matches. The new behavior requests that this ambiguity is resolved. The solution is to provide an ON clause [2].
Second issue is that we were performing queries that were essentially of this form:
```
session.query(A).filter(A.user == User(id=None))
```
Which emits SQL resembling:
```
... a WHERE ? = a.user_id
(None,)
```
This will always return False in SQL. This produced a warning before [1]. With [3] it no longer works.
Fixes #764 
Closes #767 
Reference for the SQLAlchemy changes version: 
[1] - [warnings-emitted-when-comparing-objects-with-none-values-to-relationships](docs.sqlalchemy.org/en/latest/changelog/migration_10.html#warnings-emitted-when-comparing-objects-with-none-val …

Fix issues related to SQLAlchemy 1.3

---

src/pyfaf/storage/opsys.py

In Python3 comparing unorderable types rises TypeError.
Related to c7196d4dddc6db4252eeaba6f501684739653d37

opsys: Make OpSys orderable

---

src/webfaf/config.py

We do not use flask-sqlalchemy signals[1], we are safe to disable this option.
Fixes #744
[1] http://flask-sqlalchemy.pocoo.org/dev/signals/
See also:
http://flask-sqlalchemy.pocoo.org/2.3/config/

webfaf:config: Disable SQLALCHEMY_TRACK_MODIFICATIONS

---

src/webfaf/forms.py
src/webfaf/webfaf_main.py

The modified queries produce SQL:
In `webfaf_main`:
```sql
SELECT DISTINCT ON (opsyscomponents.name) opsyscomponents.name AS opsyscomponents_name
FROM opsyscomponents
WHERE EXISTS
(SELECT 1 FROM reports
WHERE reports.component_id = opsyscomponents.id)
```
In `forms`:
```sql
SELECT opsyscomponents.id AS opsyscomponents_id, opsyscomponents.name AS opsyscomponents_name
FROM opsyscomponents
WHERE EXISTS
(SELECT 1 FROM reports
WHERE reports.component_id = opsyscomponents.id)
```
Fixes #761

webfaf: Speed up component list queries

---

docker/files/usr/bin/run_faf

With new version of httpd `apachectl` no longer accepts the `-DFOREGROUND` option.
`apachectl: The "-DFOREGROUND" option is not supported.`

docker: Replace apachectl with httpd to start the server

---

src/pyfaf/retrace.py

The line can be of format file:lineno[:columnno].
[sourceware.org/git/?p=elfutils.git;a=blob;f=src/addr2line.c;h=69d8d99589b27ea500df26d873847a3caa03d0a3;hb=HEAD#l798](https://sourceware.org/git/?p=elfutils.git;a=blob;f=src/addr2line.c;h=69d8d99589b27ea500df26d873847a3caa03d0a3;hb=HEAD#l798)
Fixes #770

retrace: Fix addr2line splitting

---

src/pyfaf/actions/releasedel.py
src/pyfaf/queries.py

Fix name of `duplicate` column in `MantisBug` and skip further processing if
return repo is `None`

WIP: Fix few bugs in releasedel action

---

docker/Makefile

`make run_db` in the `docker` directory was complaining about an existing user when run more than once.

Small fix to supress an error on user creation in the DB container

---

src/pyfaf/actions/fedmsg_notify.py
src/pyfaf/storage/events_fedmsg.py

Calling "list()" on db_report.component.name (abrt) created ["a","b","r","t"].
Because:
"db_report.component.name" returns the name of the component (str), ie. "abrt".
"db_problem.unique_component_names" returns a set of components, ie. {"abrt", "faf"}.
Fixes mistake in 1e6808dd0

fedmsg: Fix component names in fed-messaging msgs

---

src/pyfaf/storage/migrations/versions/Makefile.am
src/pyfaf/storage/migrations/versions/cee07a513404_drop_not_used_.py

This table was replaced with opsyscomponentsassociates in 4e56c268e3bc51d8b880393e400e8968de1ae76c

migrations: Drop opsysreleasescomponentsassociates table

---

src/pyfaf/actions/c2p.py

The current expression chokes on deleted files and vDSOs, and this
commit tweaks it to handle them gracefully.
Inspired by
https://salsa.debian.org/debian/debian-goodies/raw/master/find-dbgsym-packages.

pyfaf: actions: c2p: Update eu-unstrip regex

---

src/pyfaf/actions/c2p.py

Avoid needlessly parsing malformed lines and logging them twice (once when the parsing fails, then again when we find non-printable chars in them).

Check for lines with non-printable chars earlier

---

src/pyfaf/repos/rpm_metadata.py
tests/test_rpm_metadata.py

As the constructor collects all remaining positional arguments as URLs,
we end up receiving a tuple (usually 1-tuple) with a list as the first
element. In places where the URLs are iterated as a list, this will
quickly break things that expect strings and not lists.

pyfaf: repos: rpm_metadata: Flatten URL argument

---

faf.spec.in
src/webfaf/config.py
src/webfaf/templates/Makefile.am
src/webfaf/templates/about.md.in
src/webfaf/templates/mdpage.html
src/webfaf/templates/rstpage.html
src/webfaf/webfaf_main.py

Since there are no more RST pages, switched dependency on Flask-RSTPages
for markdown2, which renders Markdown documents to HTML.
Closes #766

webfaf: Repair "About" page

---

src/bin/faf
src/pyfaf/Makefile.am
src/pyfaf/__init__.py.in
src/webfaf/config.py
src/webfaf/templates/base.html

Display version information in web interface and add a flag (`-V`/`--verbose`) for `faf` CLI to print the same.
The number is taken from `faf-version` and stored in `faf.conf` during the build process.
Closes #664

pyfaf, webfaf: Display version number

---

tests/test_actions.py
tests/test_dnf.py
tests/test_rpm_metadata.py

It’s been obsoleted, so might as well not rely on the symlink.
Right now the symlinks aren’t created because of this (has since been
fixed):
https://github.com/rpm-software-management/createrepo_c/commit/b6f74272654bbd03448d590bc7dcb2788e331701

tests: Replace createrepo usage with createrepo_c

---

src/bin/faf

pyfaf: Call sys.exit() rather than exit()

---

docker/Dockerfile_db

- Change base image to registry.fedoraproject.org/f29/postgresql
- Update the base image during building

Update Dockerfile for db

---

src/webfaf/static/css/style.css
src/webfaf/templates/_helpers.html
src/webfaf/templates/problems/list_table_rows.html
src/webfaf/templates/reports/item.html
src/webfaf/templates/reports/list_table_rows.html

The numbers are more readable if the thousands are separated and the columns are right-aligned.

webfaf: Right-align and pretty-print counts in tables

---

src/pyfaf/storage/opsys.py
src/pyfaf/storage/report.py

Indexes created by sqlalchemy were different from those defined in migration script
from 33463768031f0e408fc06d74596450656eacdc05.

storage: Create joined idex for semver and semrel

---

src/pyfaf/opsys/centos.py

re.split produces an empty string ('') when the (in)active release variable is empty.
That causes creation of CentOS with empty ('') release.

centos: Use findall to search for (in)active releases

---

src/pyfaf/actions/pull_reports.py

After this change, reports that disappear from the master are automatically forgotten after the pull.
Still using pickles, since they're part of the standard library, though safer alternatives exist. Also, the data shouldn't grow uncontrollably now, since the reports are pruned regularly.
Resolves #736

pyfaf: pull-reports refactor

---

src/pyfaf/problemtypes/python.py

Wrong indentation in commit e40e33e177624c830a816df05b3aae8ec8bddf2 caused that line was
removed as part of Python2 cleanup in commit 71aca54f28452ffa957922d712e83b5611156cea

python: Add srcline to stacktraces

---

src/pyfaf/problemtypes/__init__.py
src/pyfaf/problemtypes/core.py
src/pyfaf/problemtypes/java.py
src/pyfaf/problemtypes/kerneloops.py
src/pyfaf/problemtypes/python.py
src/pyfaf/problemtypes/ruby.py

Seems that 2f135c7adbce687d2394b91e653fd9f83ebd9b55 ripped out the
common implementation and uses it directly in create_problems.

pyfaf: problemtypes: Drop unused code

---

src/pyfaf/actions/create_problems.py
src/pyfaf/queries.py

Seems that the create_problems action that’s been running on retrace01
for a couple of days now is spending a lot of time querying for reports.

pyfaf: create_problems: Batch invalid reports

---

src/pyfaf/actions/create_problems.py
src/pyfaf/queries.py
tests/test_queries.py

actions: create_problems: Bypass ORM when unassigning reports

---

docker/Dockerfile_local

It takes a lot of time to build the Docker image. It is annoying when
the whole build fails at the end because of an issue found by pylint
and you have to rerun the build.

docker: Do not fail local Docker build if pylint fails

---

src/bin/faf

Don't crash on a runtime error in case the user calls `faf` with no actions. Instead, output an error and print the help message.

pyfaf: Don't crash when no action is specified

---

src/webfaf/problems.py
src/webfaf/templates/problems/item.html

* Refactor the algorithm for choosing backtrace hashes for problem permalink to use the standard library.
* Warn if no hashes are found.
Fixes #815

webfaf: Fix division by zero in problem detail page

---

src/pyfaf/actions/assign_release_to_builds.py
tests/test_actions.py

Right now the action searches for all builds matching the expression and
assigns those builds to release and arch the user chose.
With this patch the action should search only for builds that are assigned to the
same arch as the one chosen by user.
Little bit more info:
https://github.com/abrt/faf/pull/528

assign-r-t-builds: Consider arch when searching for builds

---

src/pyfaf/actions/assign_release_to_builds.py

This should help to find packages like `lxpolkit-0.5.3-2.fc30.6` where release is `fc30.6`.

assign-r-t-builds: Modify the sql like search statement

---

HACKING.md
docker/Dockerfile_local
docker/Makefile
docker/files/usr/bin/faf-celery-beat
docker/files/usr/bin/faf-celery-worker
docker/files/usr/bin/run_faf
docker/openshift/faf-template.yml
src/pyfaf/celery_tasks/__init__.py
src/pyfaf/common.py

This PR introduces several changes to reduce the number of steps necessary to set up FAF, with the web UI using Celery and Redis, with three docker containers - for FAF itself, the database with the repo, package and report data, and for Redis which acts as a message broker and backend for Celery. Instructions in HACKING.md are expanded accordingly.

Streamline setup of FAF w/ Celery and Redis in containers

---

src/pyfaf/checker.py
src/pyfaf/storage/custom_types.py

No need to check for this. We removed Python2 support in the past.

pyfaf: Remove version_info checks

---

src/pyfaf/opsys/fedora.py

In Python3 urlopen throws HTTPError exception when the status code != 200.
We have a lot of old components (projects) that no longer exist (ie. [0]) and the URL
for them returns 404 (NOT FOUND) which causes a crash in `pull-associates`.
[0] https://src.fedoraproject.org/api/0//rpms/avifile

fedora: Handle exceptions with pull-associates

---

faf.spec.in
src/pyfaf/Makefile.am
src/pyfaf/__init__.py.in
src/pyfaf/actions/reposync.py
src/pyfaf/faf_rpm.py
src/pyfaf/retrace.py
src/pyfaf/storage/fixtures/__init__.py
tests/test_rpm.py

There was a name ambiguity between the `pyfaf.rpm` module and the python3 built-in `rpm` causing pylint `W0406: Module import itself (import-self)`.

Rename the pyfaf.rpm module

---

pylintrc

Add a `pylintrc` directive to avoid pyilnt `E1101: Module '%s' has no '%s' member (no-member)` in Fedora 31 builds.

Whitelist C extensions in pylintrc

---

src/pyfaf/faf_rpm.py

safe_popen uses popen function that returns result of communicate() (which is bytes/str) instead of
stdout stream.
close() call then fails because bytes/str has no `close` member.
Introduced in 490c147

faf_rpm: Use Popen instead of safe_popen

---

src/webfaf/templates/reports/item.html

Currently, the formatted title ends up retaining all newlines and
leading whitespace, leading to something quite messy. This also makes
fetching the title from gnome-abrt a bit painful. With some
trimming, we can make it be a single line again.

webfaf: templates: report: item: Fit title in one line

---

src/webfaf/static/css/style.css
src/webfaf/static/js/custom.js
src/webfaf/templates/_helpers.html
src/webfaf/templates/stats/by_date.html

Summary of changes:
* Change _Show more_ button into a link to reduce visual clutter.
* Allow toggling between shown and hidden component versions in report and problem pages. (It was only possible to show them but not hide them again before.)
* Only show the top ten crashing components of a given opsys release in the stats page with the option to show the rest on request.
Stats page before:
Stats page after:

Web UI cosmetic tweaks

---

src/pyfaf/storage/generic_table.py

Don't decode and re-encode bytestrings when saving them as LOBs. This is meaningless, wasteful and may lead to and error if the original is not valid UTF-8. Most of the calls supply bytes anyway.

storage: Skip encoding juggling when saving LOBs

---

src/pyfaf/actions/reposync.py

Do not use the `distro-release-arch` format as repo identifier in FAF logging to prevent confusing labels such as 'fedora-31-31-x86_64'

faf reposync: Fix repo name format

---

src/pyfaf/actions/c2p.py
src/pyfaf/queries.py

Fix `c2p`'s failure to find binary packages by build id (`/usr/lib/.build-id/12/34567890abcdef1234567890abcdef`). Affects retrace using FAF repos.

c2p: Find binary packages by build id

---

src/pyfaf/ureport_compat.py

I've run into this problem where ureport1 kerneloops would crash the
save-reports action during conversion from ureport1 to ureport2.
`TypeError: argument 1 must be str, not bytes`

ureport_compat: Fix encoding during ureport1to2

---

faf.spec.in
src/bin/Makefile.am
src/bin/faf
src/bin/faf-migrate-db
src/bin/faf-migrate-db.bash_completion
src/bin/faf.bash_completion

You won't have to remember all the commands from now on or type --help
to run faf commands.*
Unfortunately the autocompletion isn't lightning fast.

Add bash autocompletion for faf

---

src/pyfaf/actions/create_problems.py

We can save some time if we use more workers (threads) to process the db_reports
concurrently.
The communication with the DB is slowing down the db_report processing.
So while some of the workers are loading reports from the DB, other workers can start
processing the loaded reports.
The number of workers is limited by 'pool_size' and 'max_overflow' settings of connection engine.
(Default is 5 for pool_size and 10 for max_overflow).
Default is 4 threads.
faf create-problems -w 8
faf create-problems --max-workers 8

Create-problems speed-up

---

src/pyfaf/storage/migrations/versions/fd5dc71471cc_set_pkg_name_to_256.py

Somehow I got the `alter_column` arguments all wrong :\

Fix DB migration altering pkg name data type

---

src/pyfaf/storage/migrations/script.py.mako
src/pyfaf/storage/migrations/versions/9596a0f03838_zero_unique_reports_to_one.py
src/pyfaf/storage/migrations/versions/Makefile.am
src/pyfaf/ureport.py

When saving an incoming report, the number of unique reports in the corresponding daily/weekly/monthly summary was incremented if and only if the incoming report had `serial` of 1, i.e. it was the first report of its kind from the machine.
However, it may happen that the very first report gets lost, is delayed etc., in which case the report's `serial` field is greater than 1 and the uniqe count in the summary is set to 0 if the report is the first of its kind on the server.
This is now fixed by setting the unique count in a summary to 1 whenever we receive a new report in that period, ignoring its `serial`.
Lastly, add a database migration which sets the unique count to at least one for all the daily/weekly/monthly summaries which claim to have zero unique reports, but do have _some_ …

Avoid zero unique report counts in summaries

---

HACKING.md
docker/files/usr/bin/faf-celery-beat
src/pyfaf/celery_tasks/schedulers.py
src/pyfaf/storage/migrations/versions/Makefile.am
src/pyfaf/storage/migrations/versions/bb2289ffb392_add_tz_info_to_periodictasks.py
src/pyfaf/storage/task.py

Unnecessary `super()` call in `DBScheduleEntry` caused a crash on `faf-celery-beat.service` startup.  
Another crash was caused by comparison between timezone-aware and timezone-ignorant timestamp.  
Fixes fix #822

Fix broken Celery scheduler

---

src/pyfaf/queries.py

`releasedel` fails because there is still a reference to Bugzilla/MantisBug.
With a flush the state is synced and a bugzilla/mantis bug can be
deleted.

queries: Flush after changes

---

src/webfaf/summary.py

There is usually no release date set in database for releases and
so the releases in the plot are ordered by opsysrelease_id.
This should sort the plot graph first by opsys_id and the by versions.
Old:
```
CentOS 7 (opsysrelease_id=40,  opsys_id=1, release_date=, version=7)
Fedora 30 (opsysrelease_id=41, opsys_id=3, release_date=, version=30)
Fedora 31 (opsysrelease_id=42, opsys_id=3, release_date=, version=31)
CentOS 8 (opsysrelease_id=43,  opsys_id=1, release_date=, version=8)
Fedora 32 (opsysrelease_id=44, opsys_id=3, release_date=, version=32)
```
New:
```
CentOS 7 (opsysrelease_id=40,  opsys_id=1, release_date=, version=7)
CentOS 8 (opsysrelease_id=43,  opsys_id=1, release_date=, version=8)
Fedora 30 (opsysrelease_id=41, opsys_id=3, release_date=, version=30)
Fedora 31 …
```

webfaf: Order summary plot by Opsys and Version

---

src/pyfaf/bugtrackers/rhelbz.py

Will list ABRT bugs for Red Hat Enterprise Linux 8.

bugzilla: Add RHEL8 to Bugzilla product list

---

src/pyfaf/actions/repodel.py
tests/test_actions.py

Make `faf repodel` accept one or more `REPO` arguments, add `--all` option.

Allow deletion of multiple repos with faf repodel

---

src/pyfaf/actions/archive_reports.py
src/pyfaf/actions/save_reports.py

According to https://docs.python.org/3/library/os.html#os.scandir, it is
faster for use cases where we need information other than just the name.

pyfaf: actions: Use os.scandir where appropriate

---

src/pyfaf/opsys/fedora.py

We can just add the short name to the query and recieve less data from PDC.
(We don't need information about Fedora Docker/Atomic/Cloud/EPEL)
See:
https://pdc.fedoraproject.org/rest_api/v1/releases/?page_size=-1&short=fedora

fedora: Filter query for releases with short name

---

src/pyfaf/actions/pull_releases.py
src/pyfaf/opsys/centos.py

With configuration option SupportEOL you can select whether you want to
pull and in that way "support" EOLed releases.
With this option switched off EOLed releases won't be added to the database and
any incoming uReport from that release will be rejected as not supported.

pull-releases: Skip EOLed releases

---

src/pyfaf/actions/repodel.py
src/pyfaf/actions/repolist.py
src/pyfaf/actions/repomod.py
src/pyfaf/queries.py
tests/test_actions.py

Allow multiple `REPO` arguments to `faf repomod` ~~and `faf repoinfo`~~, using either enumeration or wildcards.  
~~Change `faf repoinfo` output format for easier parsing.~~  
Add OS and architecture info to `faf repolist` output.
Add a short `-a` option as an alternative to `--all` to `faf repodel`.

Allow wildcards with faf repo manipulation

---

src/webfaf/templates/reports/item.html

webui: Explain "problems" on report page

---

src/pyfaf/problemtypes/kerneloops.py
src/pyfaf/storage/report.py

The LOB functions in `GenericTable` handle string encoding automatically so we don't need to encode the oops file manually.
This also ensures that a string is passed to the webui and we don't have to decode on the front end either.
Fixes #816

storage: Handle oops LOBs as strings

---

src/pyfaf/actions/reposync.py
src/pyfaf/problemtypes/kerneloops.py
src/pyfaf/storage/bugzilla.py
src/pyfaf/storage/generic_table.py
src/pyfaf/storage/opsys.py
src/pyfaf/storage/report.py
tests/test_storage.py

Disallow implicit encoding and decoding of Unicode strings in `GenericTable`'s `get_lob()` and `save_lob()`. This requires callers to handle the coding the themselves and only supply byte strings.

Ameliorate LOB encoding craziness

---

src/pyfaf/storage/report.py

This PR fixes an exception caused by calling `decode()` as a member of [`NoneType`](https://github.com/abrt/faf/blob/master/src/pyfaf/storage/generic_table.py#L52), introduced with a change of src/pyfaf/storage/report.py in #876.

Prevent exception when calling decode on None

---

src/pyfaf/common.py
src/webfaf/blueprints/celery_tasks.py
src/webfaf/forms.py
tests/test_queries.py

This PR replaces some deprecated method names with their more up-to-date versions.  
`logger.warn` was deprecated as of Python 3.3 in favour of `logger.warning`.  
`assertEquals` in `unittest.TestCase` was an alias for `assertEqual` and was deprecated as of Python 3.3.  
`TextField` in WTForms was deprecated, replaced with `StringField` and will be removed completely in the future.

Fix DeprecationWarnings

---

faf.spec.in

I keep running into the following error during builds:  
`It's not recommended to have unversioned Obsoletes: Obsoletes: faf-yum`  
Not sure about the specific version to use though - 1.3.5 is the only one that I [found mentioned](https://copr.fedorainfracloud.org/coprs/g/abrt/faf-el7-devel/build/978502) anywhere. Somebody please correct me.

Add Obsoletes version for faf-yum

---

faf.spec.in
src/pyfaf/utils/Makefile.am
src/pyfaf/utils/json.py
src/webfaf/reports.py

Currently, a dictionary is being passed to jsonify() from Flask that
includes an array of Solution objects (if any exist). The result is a
TypeError, because Python classes are not JSON-serializable, hence the
need to take \_\_dict\_\_ first. Moreover, the “since” attribute of type
datetime.datetime needs to be stringified, because it’s also not
JSON-serializable.

webfaf: Fix serialization of reports with solutions

---

src/pyfaf/problemtypes/core.py
src/pyfaf/problemtypes/kerneloops.py
src/pyfaf/queries.py

A change was introduced in Fedora 27 to allow for installing multiple versions of debuginfo packages in parallel. In effect, `/usr/lib/.build-id` may contain debug files, as well, in addition to `/usr/lib/debug/.build-id`.
See https://fedoraproject.org/wiki/Changes/ParallelInstallableDebuginfo for more details.
Related: abrt/abrt#1462, abrt/abrt#1463, abrt/libreport#606

pyfaf: Accommodate for multiple debug directories

---

container/Dockerfile_db

New postgresql image:
https://bodhi.fedoraproject.org/updates/FEDORA-CONTAINER-2020-9b4488f9fe

container: db: Upgrade to Fedora 31

---

container/Dockerfile_local

tito crashed with `_curses.error: setupterm: could not find terminal`
during the Dockerfile build.
Specifying TERM env variable works around the issue.
bugzilla:
bugzilla.redhat.com/show_bug.cgi?id=1733043
- Install tito for build
- Use dnf builddep to install dependencies
- Change paths to rpms

Fix local Dockerfile build for tito changes

---

container/Dockerfile
container/Makefile

Currently, the “main” image is built by using RPMs from Copr, which
hurts reproducibility and automation, given that we have to build
everything in Copr first and only then build the container image. This
commit leaves only one Dockerfile file for production and development.
The image is built in multiple stages to prevent unwanted artifacts
staying around:
1. Build FAF RPMs
2. Upgrade system and install FAF RPMs
3. Perform post-installation setup
Additionally, this reworks the Makefile shorthands: the names for
images, pods and volumes were changed to drop the redundant suffixes
(-image, -volume), the targets that depend on files existing now
actually do depend on them and common options were moved out to
variables.

Rework container build

---

src/pyfaf/opsys/fedora.py

Product listings[0] for Fedora include releases that do not exist:
```
Fedora l
Fedora ln
Fedora pel7
Fedora pel8
```
This commit check if the version is a number (or rawhide) and skips
entries where this is not true.
Example of entry pulled from PDC:
```json
{
"release_id": "fedora-30",
"short": "fedora",
"version": "30",
"name": "Fedora",
"base_product": null,
"active": true,
"product_version": "fedora-30",
"release_type": "ga",
"compose_set": [..],
"integrated_with": null,
"sigkey": null,
"allow_buildroot_push": false,
"allowed_debuginfo_services": [],
"allowed_push_targets": [],
"bugzilla": null,
"dist_git": null
}
```
[0] https://pdc.fedoraproject.org/rest_api/v1/releases/?page_size=-1&short=fedora

opsys: Filter releases without numbered verion

---

src/pyfaf/problemtypes/core.py

SymbolSource.build_id is a string. Fallout from
a3e43889b2db7fe5a393ec6ffc6c84a28c0f0a36.
Fixes https://github.com/abrt/faf/issues/910

pyfaf: core: Use correct format specifier

---

src/webfaf/reports.py

It is not part of the BugTracker interface and is not implemented by
Mantis. I’m not sure if taking the no-retry route was intentional,
however, so this commit assumes that it was a thinko.
Related to https://github.com/abrt/faf/issues/909.

webfaf: reports: Don’t call download_bug_to_storage_no_retry()

---

src/pyfaf/repos/dnf.py

5508c07b919a159e56acaad0bd192e02297152b8 completely ignored the problem
of base package names, resulting in debuginfo and debugsource packages
having distinct builds in the database and breaking retracing. While
there is no longer a property in DNF that spits out the base name, we
can use the class attributes and strip the suffixes as needed. This
commit does just that.
Fixes https://github.com/abrt/faf/issues/919

repos: dnf: Correctly handle debug packages

---

src/pyfaf/bugtrackers/mantisbt.py

Not sure how to fully test this as building the container image still generates an image without these changes.
I am trying to build it with `podman build -f container/Dockerfile ./`
EDIT: 
```
cd faf/container
make build
```
My bad

"duplicate of" mantis bug relationships can be empty

---

src/pyfaf/actions/reposync.py

Build class has `version` as a String on https://github.com/abrt/faf/blob/1d3ccf592161be3665c1e7573b81dfb7be0c912b/src/pyfaf/storage/opsys.py#L188 but on logging is treated as a digit.
Logging while using rpmmetadata repo types was causing this:
```
[2020-06-12 10:30:23] DEBUG:faf.pyfaf.faf_rpm: qemu-kvm-common-ev-2.12.0-44.1.el7_8.1.x86_64 contains 139 files
[2020-06-12 10:30:23] DEBUG:faf.RepoSync: [3 / 8] Processing package qemu-kvm-common-ev
--- Logging error ---
Traceback (most recent call last):
File "/usr/lib64/python3.8/logging/__init__.py", line 1081, in emit
msg = self.format(record)
File "/usr/lib64/python3.8/logging/__init__.py", line 925, in format
return fmt.format(record)
File "/usr/lib64/python3.8/logging/__init__.py", line 664, in format
record.message = …
```

logging: Fix log formatting for build logs

---

src/webfaf/forms.py
src/webfaf/reports.py
src/webfaf/static/css/style.css
src/webfaf/templates/_helpers.html
src/webfaf/templates/problems/item.html
src/webfaf/templates/problems/list_table_rows.html
src/webfaf/templates/reports/item.html

**What's the problem?**
Right now there is no way how to dissociate a bug from report that was
added by mistake.
**How does this commit help?**
This commit adds a small button (trashcan) in front of links to
bugzillas. The button is only available (visible) to component maintainers.
They can use it to dissociate bugs from reports. Modal window appears after
clicking on the trashcan to confirm dissociation action.
<h1>Screenshots:</h1>
Button appears when report has an associated bug:
Modal after clicking on trashcan:
Bug dissociated successfuly:
External bugs on Problem list page:
Fixes: #599

webfaf: Disassociate bug from report

---

faf.spec
requirements.txt
src/webfaf/webfaf_main.py

Werkzeug's `contrib.cache` and `contrib.fixers` have been deprecated since 0.15 and removed in 1.0. This PR updates the imports to reflect these changes in the API.
A new dependency, `python3-cachelib`, is added to the spec file as well as an an explicit dependency on `python3-werkzeug`.
Resolves #905

Werkzeug 1.0 migration

---

src/pyfaf/queries.py
src/pyfaf/storage/report.py
src/webfaf/reports.py

Currently, the code assumes that any new report association with an
external tracker bug will be strictly Bugzilla, which is not the only
tracker FAF supports. This commit fixes that by adding synonyms to
report tables in order to achieve some kind of genericity along with
dynamic inspection of selected bug tracker on POST to
/\<report\>/associate_bz.
The same issue applies to disassociation, where the situation is a bit
more complex, in that we don’t know what tracker we’re using beforehand,
so this commit adds a new database query method that iterates all of
them.
Closes https://github.com/abrt/faf/issues/924

webfaf: reports: Fix non-Bugzilla bug association

---

README.md

IIRC the `faf-devel` COPR repository was deleted and replaced with
`faf-el8-devel`.

readme: Fix link to devel build status

---

src/pyfaf/problemtypes/core.py
tests/sample_reports/d856f816-6fad-46a3-baea-53673646bb72
tests/sample_reports/unikhod_failnejm
tests/test_webfaf/test_reports.py

Currently, when building a list of symbol strings, the file name ends up
being converted to ASCII and added to a Unicode string, which somehow
results in the byte-literal prefix being stored verbatim, which further
results in inconsistent hashes for identical crash threads.
This commit drops the encoding bit.
Closes https://github.com/abrt/faf/issues/922

pyfaf: problemtypes: core: Don’t ASCII-encode file names

---

src/pyfaf/actions/addcompathashes.py

Commit [0] removed only usage of hashlib and pylint is now complaining about
unused import.
[0] https://github.com/abrt/faf/commit/75f0d64a8214d3f303434fb8dc3c1cfa0c9d0daf

addcompathashes: Remove import of hashlib

---

container/openshift/faf-database-template.yml
container/openshift/faf-template.yml

The container image names were renamed 4 months ago to `faf` and `faf-db`.
Fixes #944

openshift: Fix docker image names

---

container/Dockerfile

With `COPY . /src` in the Dockerfile it assumed that `origin`
was pointing to `https://github.com/abrt/faf.git`.
If that wasn't true (like in my case, origin=git@github.com:abrt/faf.git)
`tito build` didn't have permissions (ssh key) to check the remote repo
and failed with `Tag does not exist in remote git repo`.

dockerfile: Fix build stage

---

container/Dockerfile
container/Dockerfile_local

When using `COPY` with more than one source file, the destination must be a directory and end with a `/`  
See latest [quay.io build](https://quay.io/repository/abrt/faf/build/787288ad-2879-4a2e-a90f-d2a424fda9ae).

container: Dockerfile: Fix dest arg to COPY

---

src/pyfaf/storage/generic_table.py
src/webfaf/reports.py

- Encode the JSON of an invalid report to a bytestring before saving it as a LOB.
- Add typing annotations to all methods of `GenericTableBase`.
- Add casts where necessary.
- Improve an error message in `save_lob()` to report the name of the LOB.
- Fix minor issues reported by Pylint.
Resolves #954

Fix LOB saving issue

---

config/celery-beat-env.conf
config/celery-worker-env.conf
container/files/usr/bin/faf-celery-beat
container/files/usr/bin/faf-celery-worker
init-scripts/faf-celery-beat.service
init-scripts/faf-celery-worker.service

Celery 5.0 removed support of global options after sub-command.
Changes still work in older Celery versions (4.x is used in CentOS 8).
The error message from Celery 5.0:
You are using `-A` as an option of the beat sub-command:
celery beat -A celeryapp <...>
The support for this usage was removed in Celery 5.0. Instead you should use `-A` as a global option:
celery -A celeryapp beat <...>
See for more info:
https://docs.celeryproject.org/en/stable/whatsnew-5.0.html#step-1-adjust-your-command-line-invocation
You can run and schedule actions from frontend and even see the results:

Fix deprecated Celery invocation with global options

---

config/plugins/web.conf
src/webfaf/config.py
src/webfaf/templates/base.html

Add a quick and dirty way of putting up a banner notifying all visiors
of scheduled maintenance and similar issues.
While I was adding the possible discontinuation notice to fafreport, I thought I migh as well make it general purpose for similar occasions.

webfaf: Add ad-hoc banner

---

container/Dockerfile_db

The pg-semver-0.30.0-1 package, the only version available for the
f31/postgresql docker image from registry.fedoraproject.org, which we're
using for the faf-db container, has the wrong default version 0.22.0 set
in `/usr/share/pgsql/extension/semver.control`, making it impossible to
create the extension and subsequently to run DB migrations and initialize
FAF.
~~This is just a temporary solution until the f32/postgresql image becomes
available.~~
See also https://github.com/theory/pg-semver/issues/53, the issue seems
to have been fixed upstream.

Dockerfile_db: Update to f33/postgresql

---

container/README.md

Some commands used old names of containers.
Related: https://github.com/abrt/faf/issues/908

container: Fix some podman commands in container readme

---

README.md

Add link to the container specific page on Github.
THis page also shows the readme file.
Related: https://github.com/abrt/faf/issues/908

README: Reference the container readme

---

config/plugins/fedora.conf

Add the nonsensical releases "ln" and "l" which appeared recently in the JSON output from Fedora Product Definition Center.

Update pattern for ignored Fedora releases

---

src/webfaf/blueprints/celery_tasks.py

Fallout from https://github.com/abrt/faf/pull/967. Type annotation
without futures causes a crash when accessing the FAF web interface
because the class in the annotation is only defined later in the file.
Moving the code around causes the same issue with a different class so
I'm just dropping the annotation.

celery_tasks: Remove future-dependent annotation

---

.git-commit-template
HACKING.md

To start using this template:
$ git config commit.template .git-commit-template

Add a commit message template

---

faf.spec
pylintrc
requirements.txt
src/pyfaf/bugtrackers/bugzilla.py
src/pyfaf/repos/rpm_metadata.py

* Use `urllib` instead of a dedicated library for simple HTTP requests.
* Small refactoring here and there.
* Add type annotations.

Drop pycurl dependency

---

src/pyfaf/opsys/centos.py
src/pyfaf/opsys/fedora.py

When retrieving the list of active Fedora releases from Fedora PDC, only consider GA (general availability) releases, i.e. ignore `*-updates`, `*-updates-testing` etc.
This should prevent EOL'd release from reappearing on the summary page, since `faf pull-releases` used to switch their state to `ACTIVE` back from `EOL` due to the confusion in release types.

Only accept Fedora GA releases

---

src/pyfaf/storage/opsys.py

Ignore one instance of the "Instance X has no Y member" Pylint error. `OpSys.releases` is a backref from `OpSysReleases`.

storage: Ignore Pylint error

---

CHANGELOG.md
src/pyfaf/actions/pull_components.py

Do not download new components for EOL releases since we are not really interested in them anymore and it's wasting CPU time.

Do not pull components for EOL releases

---

CHANGELOG.md
Makefile.am
faf.spec
init-scripts/faf-celery-tmpfiles.conf
init-scripts/faf.conf
src/pyfaf/common.py
src/pyfaf/faf_rpm.py

* Extract RPMs during `faf retrace` into a separate directory inside `/tmp/faf`.
* Add config for systemd-tmpfiles to clean up `/tmp/faf` regularly.
* Small code style improvements.
See individual commits for more details.
Fixes #979

Add configuration for systemd-tmpfiles

---

faf.spec
tests/faftests/__init__.py

* The `dbname` parameter has been changed to `database` in python-testing.sqlalchemy.
* Bump dependency on python-testing.postgresql in spec file.

Fix build on Fedora 34+

---

src/webfaf/reports.py
tests/test_webfaf/test_reports.py

Return actual exception to reporter when an uReport is rejected. So far,
this was only done in one specific situation and otherwise an overly
generic error message was returned.
Resolves: https://github.com/abrt/faf/issues/461

More informative error message on invalid uReport

---

CHANGELOG.md
faf.spec
requirements.txt

Bump Celery dependency due to the [CVE-2021-23727][1] vulnerability which affects Celery versions prior to 5.2.2.
[1]: https://github.com/advisories/GHSA-q4xr-rc97-m4xx

Require Celery >= 5.2.2

---

src/webfaf/templates/base.html

Solves issue #1008 Remove the “Report a bug” link from the footer

Deletes "Report a Bug" option

---

CHANGELOG.md
faf.spec
requirements.txt
src/webfaf/config.py
src/webfaf/webfaf_main.py

Sending alerts for exception should not be a responsibility of the application but a monitoring system. Moreover, the SMTP handler is not configured correctly in production and only clutters log files with exceptions.

Remove SMTP logging handler

---

src/pyfaf/config.py

`SafeConfigParser` has been renamed in Python 3.2 and will be removed in Python 3.12.

Update config parser class name

---

CHANGELOG.md
faf.spec

We are using some features of the 3.6 language in code and do not feel like supporting older versions. Even RHEL 8 is on 3.6 so this should be fine for all the cases we want to support.

Require Python 3.6

---

CHANGELOG.md
src/pyfaf/opsys/centos.py
src/pyfaf/opsys/fedora.py
tests/sample_reports/ureport_caret
tests/test_ureport.py

The [Fedora packaging guidelines][1] require a caret to be used in the version string for package snaphots.
[1]: https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/#_snapshots
Fixes #484

opsys: Allow carets in package version

---

src/pyfaf/problemtypes/core.py

Virtual dynamic shared objects can appear in the stacktrace, and they don't have a file name as they are provided by the kernel.

Make "file_name" an optional field in the ureport
